name: Release

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Keycloak branch'
        required: true
      version:
        description: 'New version'
        required: true
      previous-version:
        description: 'Old version'
        required: true

concurrency: rel-${{ github.ref }}

defaults:
  run:
    shell: bash

jobs:

  show-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Version: ${{ inputs.version }}  " >> $GITHUB_STEP_SUMMARY
          echo "Release branch: ${{ inputs.branch }}  " >> $GITHUB_STEP_SUMMARY
          echo "Previous Keycloak version: ${{ inputs.previous-version }}  " >> $GITHUB_STEP_SUMMARY
          echo "Workflow branch: ${{ github.ref_name }}  " >> $GITHUB_STEP_SUMMARY

  env:
    uses: ./.github/workflows/x-env.yml

  publish-keycloak-operator-hub:
    name: Publish Keycloak Operator to OperatorHub
    needs: [ env]
    uses: ./.github/workflows/x-keycloak-operator-hub-publish.yml
    with:
      version: ${{ github.event.inputs.version }}
      community-operators-org: ${{ needs.env.outputs.community-operators-org }}
      prod-operators-org: ${{ needs.env.outputs.prod-operators-org }}
      release-bot-email: ${{ needs.env.outputs.release-bot-email }}
      release-bot-name: ${{ needs.env.outputs.release-bot-name }}
    secrets:
      RELEASE_BOT_PRIVATE_KEY: ${{ secrets.RELEASE_BOT_PRIVATE_KEY }}