name: X Keycloak JS
on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
    secrets:
      GH_ORG:
        required: true
      GH_TOKEN:
        required: true
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.GH_ORG }}/keycloak
          token: ${{ secrets.GH_TOKEN }}
          ref: ${{ inputs.tag }}
          path: keycloak

      - name: Move directory
        run: mv keycloak/adapters/oidc/js/* . && rm -r keycloak

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          check-latest: true
          cache: npm

      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: npm ci

      - name: Create package tarball
        run: |
          npm run prepublishOnly
          npm pack
          mv -T *.tgz keycloak-js.tgz

      - name: Upload to GitHub Releases
        run: gh release upload ${{ inputs.tag }} --repo ${{ secrets.GH_ORG }}/keycloak keycloak-js.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
